name: "Terraform"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Plan:
    uses: viictorivo/OrderingSystem/.github/workflows/plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Apply:
    needs: Plan
    uses: viictorivo/OrderingSystem/.github/workflows/apply.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}